[package]
name = "obj"
version = "0.1.0"
authors = ["outamaa <ville.outamaa@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
geometry = { path = "../../geometry" }
gfx = { path = "../../gfx" }
emscripten_main_loop = "0.1.1"
loader = { path = "../../loader" }
math = { path = "../../math" }
sdl2 = "0.34"